version: '3.8'

services:
  sqlserverdb:
     image: mcr.microsoft.com/mssql/server:2019-latest
     restart: always
     environment:
       ACCEPT_EULA: 'Y'
       MSSQL_SA_PASSWORD: 'Password12*'
     ports:
     - "1433:1433"

  rabbitmq:
     image: rabbitmq:3-management
     restart: always
     ports:
     - "5672:5672"
     - "15672:15672"